In [1]:
import pickle
import pandas as pd

In [ ]:
car_dict = {
    "Levy": 1399,
    "Manufacturer": "LEXUS",
    "Model": "RX 450",
    "Prod_year": 2010,
    "Category": "Jeep",
    "Leather_interior": "Yes",
    "Fuel_type": "Hybrid",
    "Engine_volume": 3.5,
    "Mileage": 186005,
    "Cylinders": 6.0,
    "Gear_box_type": "Automatic",
    "Drive_wheels": "4x4",
    "Wheel": "Left wheel",
    "Color": "Silver",
    "Airbags": 12
}

In [3]:
data = pd.DataFrame([car_dict])
data

,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Wheel,Color,Airbags
0,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005,6.0,Automatic,4x4,Left wheel,Silver,12

In [4]:
from datetime import datetime

data['Age'] = datetime.now().year - data['Prod. year']

data = data.drop(columns=['Doors', 'Prod. year'], errors='ignore')

In [5]:
data

,Levy,Manufacturer,Model,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Wheel,Color,Airbags,Age
0,1399,LEXUS,RX 450,Jeep,Yes,Hybrid,3.5,186005,6.0,Automatic,4x4,Left wheel,Silver,12,16

In [6]:
one_hot_columns = ['Leather interior', 'Gear box type', 'Drive wheels', 'Wheel']

with open('../models/one_hot_encoder.pkl', 'rb') as f:
    one_hot_encoder = pickle.load(f)

In [7]:
# 4. Label Encode Categorical Columns
label_encode_columns = ['Manufacturer', 'Model', 'Category', 'Fuel type', 'Color']

# Load the saved label encoders
with open('../models/label_encoders.pkl', 'rb') as f:
    label_encoders = pickle.load(f)

# Apply label encoding
for column in label_encode_columns:
    le = label_encoders[column]
    data[column] = le.transform(data[column])

In [8]:
data

,Levy,Manufacturer,Model,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Wheel,Color,Airbags,Age
0,1399,28,1037,4,Yes,2,3.5,186005,6.0,Automatic,4x4,Left wheel,12,12,16

In [9]:
# 5. Scale column
numerical_columns = ['Levy', 'Engine volume', 'Mileage', 'Age']

with open('../models/scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)
    
data[numerical_columns] = scaler.transform(data[numerical_columns])

In [10]:
data.columns

Index(['Levy', 'Manufacturer', 'Model', 'Category', 'Leather interior',
       'Fuel type', 'Engine volume', 'Mileage', 'Cylinders', 'Gear box type',
       'Drive wheels', 'Wheel', 'Color', 'Airbags', 'Age'],
      dtype='object')

In [11]:
with open('../models/model.pkl', 'rb') as f:
    model = pickle.load(f)

In [14]:
import pandas as pd

data_encoded = pd.get_dummies(data)
train_columns = model.feature_names_in_

data_encoded = data_encoded.reindex(columns=train_columns, fill_value=0)

predictions = model.predict(data_encoded)
print(predictions)

[12404.219]