In [31]:
import numpy as np
import pandas as pd
import preprocessing
data = pd.read_csv('./car_price_prediction.csv')
data.head()

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

In [32]:
data = preprocessing.preprocessing_pipeline(data)

Preprocessing started...
Initial shape: (19237, 18)
After dropping duplicates: (18924, 18)
Replacing categorical values...
After cleaning outliers: (16037, 18)
Feature engineering...
Drooping columns...
Final shape:  (16037, 16)

In [33]:
data.head()

,Price,Levy,Manufacturer,Model,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Wheel,Color,Airbags,Age
0,13328,1399,LEXUS,RX 450,Jeep,Yes,Hybrid,3.5,186005,6.0,Automatic,4x4,Left wheel,Silver,12,16
1,16621,1018,CHEVROLET,Equinox,Jeep,No,Petrol,3.0,192000,6.0,Tiptronic,4x4,Left wheel,Black,8,15
2,8467,0,HONDA,FIT,Hatchback,No,Petrol,1.3,200000,4.0,Variator,Front,Right-hand drive,Black,2,20
3,3607,862,FORD,Escape,Jeep,Yes,Hybrid,2.5,168966,4.0,Automatic,4x4,Left wheel,White,0,15
4,11726,446,HONDA,FIT,Hatchback,Yes,Petrol,1.3,91901,4.0,Automatic,Front,Left wheel,Silver,4,12

In [ ]:

from sklearn.preprocessing import LabelEncoder
one_hot_columns = ['Leather interior', 'Gear box type', 'Drive wheels', 'Wheel']

data = pd.get_dummies(data, columns=one_hot_columns)

label_encode_columns = ['Category', 'Fuel type','Color']

label_encoder = LabelEncoder()

for column in label_encode_columns:
    data[column] = label_encoder.fit_transform(data[column])
data

,Price,Levy,Manufacturer,Model,Category,Fuel type,Engine volume,Mileage,Cylinders,Color,...,Leather interior_Yes,Gear box type_Automatic,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive
0,13328,1399,LEXUS,RX 450,4,2,3.5,186005,6.0,12,...,True,True,False,False,False,True,False,False,True,False
1,16621,1018,CHEVROLET,Equinox,4,5,3.0,192000,6.0,1,...,False,False,False,True,False,True,False,False,True,False
2,8467,0,HONDA,FIT,3,5,1.3,200000,4.0,1,...,False,False,False,False,True,False,True,False,False,True
3,3607,862,FORD,Escape,4,2,2.5,168966,4.0,14,...,True,True,False,False,False,True,False,False,True,False
4,11726,446,HONDA,FIT,3,5,1.3,91901,4.0,12,...,True,True,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,8467,0,MERCEDES-BENZ,CLK 200,1,0,2.0,300000,4.0,12,...,True,False,True,False,False,False,False,True,True,False
19233,15681,831,HYUNDAI,Sonata,9,5,2.4,161600,4.0,11,...,True,False,False,True,False,False,True,False,True,False
19234,26108,836,HYUNDAI,Tucson,4,1,2.0,116365,4.0,7,...,True,True,False,False,False,False,True,False,True,False
19235,5331,1288,CHEVROLET,Captiva,4,1,2.0,51258,4.0,1,...,True,True,False,False,False,False,True,False,True,False
19236,470,753,HYUNDAI,Sonata,9,2,2.4,186923,4.0,14,...,True,True,False,False,False,False,True,False,True,False

In [35]:
x = data.drop('Price', axis=1)
y = data['Price']

In [36]:
from sklearn.model_selection import train_test_split
x_train, x_temp , y_train , y_temp = train_test_split(x, y, test_size = 0.3, random_state = 42)

x_val, x_test , y_val , y_test = train_test_split(x_temp, y_temp, test_size = 0.5, random_state = 42)

print(f"Train set: {len(x_train)} samples")
print(f"Validation set: {len(x_val)} samples")
print(f"Test set: {len(x_test)} samples")

Train set: 11225 samples
Validation set: 2406 samples
Test set: 2406 samples

In [37]:
target_encoding_columns = [ 'Fuel type', 'Model','Airbags','Cylinders','Manufacturer']
train = pd.concat([x_train, y_train], axis=1)
for col in target_encoding_columns:
    mean_encoded = train.groupby(col)['Price'].mean()
    global_mean = train['Price'].mean()
    x_train[col] = x_train[col].map(mean_encoded).fillna(global_mean)
    x_val[col] = x_val[col].map(mean_encoded).fillna(global_mean)
    x_test[col] = x_test[col].map(mean_encoded).fillna(global_mean)

In [ ]:
x_train

,Levy,Manufacturer,Model,Category,Fuel type,Engine volume,Mileage,Cylinders,Color,Airbags,...,Leather interior_Yes,Gear box type_Automatic,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive
11672,531,19753.516926,15868.180380,9,13671.306794,1.6,96860,14780.234271,14,19525.888567,...,True,True,False,False,False,False,True,False,True,False
16412,1249,19753.516926,28322.619718,7,20214.696933,2.5,32578,14780.234271,12,19525.888567,...,True,True,False,False,False,False,True,False,True,False
12400,784,11069.031773,17176.835294,3,13671.306794,1.5,1461,14780.234271,12,19525.888567,...,True,True,False,False,False,False,True,False,True,False
15139,0,11574.503817,6814.869565,9,7497.828571,1.6,30000,14780.234271,10,9250.583333,...,False,False,True,False,False,False,True,False,True,False
8666,0,9778.494318,15681.000000,10,13671.306794,2.0,150000,14780.234271,14,10096.183161,...,True,False,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16106,1273,29514.569079,28936.254386,4,20214.696933,2.7,77016,14780.234271,12,19525.888567,...,True,True,False,False,False,False,True,False,True,False
6437,765,9860.837209,5331.000000,9,13671.306794,2.0,70395,14780.234271,14,10091.405039,...,True,True,False,False,False,False,True,False,True,False
1011,0,13215.376664,8967.117647,3,13671.306794,1.8,99000,14780.234271,14,8967.025862,...,False,True,False,False,False,False,True,False,True,False
18952,1172,14871.384354,15957.928571,4,13671.306794,3.5,122323,12338.707700,7,19395.619503,...,False,False,False,True,False,True,False,False,True,False
8683,1211,12541.181244,32929.000000,4,20214.696933,3.0,130000,12338.707700,1,10091.405039,...,True,False,False,True,False,True,False,False,True,False

In [39]:
from sklearn.preprocessing import StandardScaler
numerical_columns = ['Levy', 'Engine volume', 'Mileage', 'Age','Fuel type', 'Model','Airbags','Cylinders','Manufacturer']
scaler = StandardScaler()

x_train[numerical_columns] = scaler.fit_transform(x_train[numerical_columns])
x_val[numerical_columns] = scaler.transform(x_val[numerical_columns])
x_test[numerical_columns] = scaler.transform(x_test[numerical_columns])

All Data Is Scaled (Manufacturer is not scaled that before add scaler)
R^2 Score in target encoding is better than training without target encoding
R^2 Score It will get better after added Random Forest Regressor
R^2 Score in without target encoding it will get better after added Random Forest Regressor

In [ ]:
x_train

,Levy,Manufacturer,Model,Category,Fuel type,Engine volume,Mileage,Cylinders,Color,Airbags,...,Leather interior_Yes,Gear box type_Automatic,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive
11672,-0.093514,1.257138,0.218770,9,-0.192604,-0.891685,-0.413703,0.405215,14,1.151873,...,True,True,False,False,False,False,True,False,True,False
16412,1.483676,1.257138,2.013191,7,1.664946,0.609064,-1.216760,0.405215,12,1.151873,...,True,True,False,False,False,False,True,False,True,False
12400,0.462237,-0.763238,0.407320,3,-0.192604,-1.058434,-1.605496,0.405215,12,1.151873,...,True,True,False,False,False,False,True,False,True,False
15139,-1.259932,-0.645644,-1.085620,9,-1.945143,-0.891685,-1.248966,0.405215,10,-1.134753,...,False,False,True,False,False,False,True,False,True,False
8666,-1.259932,-1.063471,0.191802,10,-0.192604,-0.224685,0.250160,0.405215,14,-0.946577,...,True,False,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16106,1.536396,3.527970,2.101603,4,1.664946,0.942564,-0.661608,0.405215,12,1.151873,...,True,True,False,False,False,False,True,False,True,False
6437,0.420500,-1.044315,-1.299414,9,-0.192604,-0.224685,-0.744323,0.405215,14,-0.947640,...,True,True,False,False,False,False,True,False,True,False
1011,-1.259932,-0.263908,-0.775526,3,-0.192604,-0.558185,-0.386969,0.405215,14,-1.197855,...,False,True,False,False,False,False,True,False,True,False
18952,1.314534,0.121349,0.231701,4,-0.192604,2.276562,-0.095601,-1.893112,7,1.122883,...,False,False,False,True,False,True,False,False,True,False
8683,1.400204,-0.420754,2.676873,4,1.664946,1.442813,0.000306,-1.893112,1,-0.947640,...,True,False,False,True,False,True,False,False,True,False

In [41]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [42]:
# this code i added numpy and sqrt to solve the error
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

y_val_pred = lr.predict(x_val)

rmse = np.sqrt(mean_squared_error(y_val, y_val_pred))
r2 = r2_score(y_val, y_val_pred)

print(f"Root Mean Squared Error: {rmse}")
print(f"R^2 Score : {r2}")

Root Mean Squared Error: 8118.740467306492
R^2 Score : 0.4674953913982821

In [43]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

rf = RandomForestRegressor()
rf.fit(x_train, y_train)
y_val_pred = rf.predict(x_val)

rmse = np.sqrt(mean_squared_error(y_val, y_val_pred))
r2 = r2_score(y_val, y_val_pred)

print(f"Root Mean Squared Error: {rmse}")
print(f"R^2 Score : {r2}")

Root Mean Squared Error: 5637.391435654504
R^2 Score : 0.7432547387777766